version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rust-api-container
    environment:
      DATABASE_URL: "postgres://myuser:mypass@db:5432/mydb"
      HOST: "0.0.0.0"
      PORT: "8080"
      RUST_LOG: "info"
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "
      diesel migration run &&
      /app/api"

volumes:
  postgres-data:
